WARNING:root:tmoney
WARNING:root:[Errno 5] Input/output error
ERROR:apscheduler.executors.default:Job "crawlingTmoneyBusEveryDay (trigger: cron[hour='15', minute='42', second='0'], next run at: 2020-08-28 15:42:00 KST)" raised an exception
Traceback (most recent call last):
  File "app.py", line 43, in crawlingTmoneyBusEveryDay
    tmoney_crawling.main()
  File "/home/nunchi/server/tmoney_crawling.py", line 33, in main
    print("tbus start!!!!")
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "app.py", line 45, in crawlingTmoneyBusEveryDay
    print(ex)
OSError: [Errno 5] Input/output error
ERROR:apscheduler.executors.default:Job "crawlingKobusEveryDay (trigger: cron[hour='15', minute='42', second='0'], next run at: 2020-08-28 15:42:00 KST)" raised an exception
Traceback (most recent call last):
  File "app.py", line 35, in crawlingKobusEveryDay
    kobus_crawling.main()
  File "/home/nunchi/server/kobus_crawling.py", line 45, in main
    print("kobus start!!!")
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "app.py", line 37, in crawlingKobusEveryDay
    print(ex)
OSError: [Errno 5] Input/output error
